site_name: "Documentation | Plug"
site_author: plugwallet.ooo
site_description: Plug is a browser crypto wallet extension that allows you to access your ICP, Cycles, and other tokens as well as log into IC apps with one click.
site_url: https://docs.plugwallet.ooo/
copyright: 'Â© 2021 Built by Fleek'
repo_name: psychedelic/plug-docs
repo_url: https://github.com/psychedelic/plug-docs
theme:
  name: material
  custom_dir: overrides
  favicon: './imgs/favicon.ico'
  logo: './imgs/logo.png'
  font:
    text: 'Open Sans'
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/codehilite-theme.css'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: true
nav:
  - Welcome to Plug ðŸ‘‹: index.md
  - Getting Started ðŸ”Œ:
    - Introduction: getting-started/connect-to-plug/#browser-extension
    - Connect to Plug: getting-started/connect-to-plug/#requestconnectrequestconnectparams
    - Signing Requests: getting-started/connect-to-plug/#createactor
    - Query Balances / Info: getting-started/connect-to-pslug/#requestbalance
    - Trigger Transactions : getting-started/connect-to-plug/#requesttransfersendicptsargs
    - Authentication Button : getting-started/plug-button.md
  - Build an App Examples ðŸ’¡: 
    - Buy me a Coffee: build-an-app-examples/build-app-buy-me-a-coffee.md
    - Plugged (E2E): build-an-app-examples/build-app-plugged.md
    - NNS Stats: build-an-app-examples/plug-auth-nns.md
    - Coinflip: "https://2ji5m-raaaa-aaaah-aanoa-cai.raw.ic0.app"
  - Common Terms ðŸ““: common-terms/plug-dictionary.md    
  - Resources ðŸ§°:
    - Resource Library: resources/library.md
    - Migrating Curves: resources/migrating-curve.md
    - The Internet Computer: "https://dfinity.org/faq"
    - Disclaimer: resources/disclaimer.md
    - Trademark: resources/trademark.md
    - Privacy: resources/privacy.md
  - Our App Ecosystem ðŸŒ€: resources/apps-with-plug.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/psychedelic/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/plug_wallet
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yVEcEzmrgm