site_name: "Documentation | Plug"
site_author: plugwallet.ooo
site_description: Plug is a browser crypto wallet extension & mobile app that allows you to access your ICP, Cycles, and other tokens as well as log into IC apps with one click.
site_url: https://docs.plugwallet.ooo/
copyright: '¬© 2021 Built by Fleek'
repo_name: psychedelic/plug
repo_url: https://github.com/psychedelic/plug
theme:
  name: material
  custom_dir: overrides
  favicon: './imgs/favicon.ico'
  logo: './imgs/logo.png'
  font:
    text: 'Open Sans'
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/codehilite-theme.css'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: true
nav:
  - Welcome to Plug üëã: index.md
  - <b>Developer Guides</b> üß∞:
    - Getting Started: getting-started/extension-components.md
    - Connect apps to Plug: getting-started/connect-to-plug.md
    - Using the Agent/Actor: getting-started/making-calls.md
    - Balances and Transactions: getting-started/balances-transactions.md
    - Mobile Auth Alpha: getting-started/alpha-wallet-connect.md
  - <b>Assets in Plug</b> üé®:
    - Tokens: getting-started/custom-tokens.md
    - Non-fungible Tokens (NFTs): getting-started/nfts.md
  - <b>Build an App Examples</b> üí°:
    - Authentication Button: build-an-app-examples/plug-button.md
    - Buy me a Coffee: build-an-app-examples/build-app-buy-me-a-coffee.md
    - Plugged (E2E): build-an-app-examples/build-app-plugged.md
    - NNS Stats: build-an-app-examples/plug-auth-nns.md
    - Coinflip: "https://2ji5m-raaaa-aaaah-aanoa-cai.raw.ic0.app"  
  - <b>Resources & FAQs </b> üìö:
    - FAQs: resources/faq.md
    - Resource Library: resources/library.md
    - Common Terms: common-terms/plug-dictionary.md  
    - Disclaimer: resources/disclaimer.md
    - Trademark: resources/trademark.md
    - Privacy: resources/privacy.md
  - <b>Troubleshooting</b> ‚ùì:  
    - Troubleshooting Guides: resources/troubleshooting.md
    - Recovering Sub-accounts: resources/multiple-accounts.md
    - Migrating Curves: resources/migrating-curve.md    
    - Depositing Cycles: resources/buying-cycles.md
    - App Trust & Security: resources/app-trust-and-security.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/psychedelic/plug/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/plug_wallet
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yVEcEzmrgm