site_name: "Documentation | Plug"
site_author: plugwallet.ooo
site_description: Plug is a browser crypto wallet extension that allows you to access your ICP, Cycles, and other tokens as well as log into IC apps with one click.
site_url: https://docs.plugwallet.ooo/
copyright: 'Â© 2021 Built by Fleek'
repo_name: psychedelic/plug-docs
repo_url: https://github.com/psychedelic/plug-docs
theme:
  name: material
  custom_dir: overrides
  favicon: './imgs/favicon.ico'
  logo: './imgs/logo.png'
  font:
    text: 'Open Sans'
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - meta
  - toc:
      permalink: true
nav:
  - Welcome to Plug ğŸ‘‹: index.md
  - Sneak Peek ğŸ‘€: introduction/overview.md
  - Getting Started ğŸ”Œ:
    - Integrate Plug: getting-started/integrate-plug.md
    - Interact with Accounts: getting-started/interact-with-accounts.md
    - Trigger Transactions : getting-started/trigger-transactions.md
    - Add a Custom Token: getting-started/trigger-transactions.md
  - Common Terms ğŸ““: common-terms/plug-dictionary.md
  - IC Provider API ğŸ¤: ic-provider-api/universal-ic-object.md    
  - Resources ğŸ§°:
    - Resource Library: resources/library.md
    - The Dank Protocol: "https://dank.ooo"
    - The Internet Computer: "https://dfinity.org/faq"
    - Disclaimer: resources/disclaimer.md
    - Trademark: resources/trademark.md
    - Privacy: resources/privacy.md
  - Our App Ecosystem ğŸŒ€: resources/apps-with-plug.md
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/FleekHQ/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/plug_wallet
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yVEcEzmrgm